# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatwright" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "bcd2e2cd8f545a562465a79b09da2a97cb635745dfb346097fc3070793891978"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ea21c302e700d31d49279d8dcb526864b0084cb99819840a8bd4319bccc19377"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "41ca21b83cb46da86a85e29203e0e6903b72e973f4778a3e884767e02e87a293"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4e36214e4df7f07f1fc0b6d0e5c55985418ad2b52220d76b63d284c395d21828"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chatwright"
  desc "Chatwright CLI — deterministic and AI-driven testing for conversational applications."
  homepage "https://chatwright.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatwright"

  # No zap stanza required
end
