# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatwright" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "7df059d97c5eae4e69d430e892c124f8df2578f04235f87bda718cf8bfe5fe3c"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78832cd51bf17b2f095e057c25da0a9b07bd9e8f6c38ebfbd3e9ce0f9fb846b5"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ad61f7db711b116a356fbc51de901a6173b832048c9f45d8dbccc6ab37559f5"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "21d35038328a2f11702585419ea31f05033afd562d3785464a3b14cca6761dbb"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chatwright"
  desc "Chatwright CLI — deterministic and AI-driven testing for conversational applications."
  homepage "https://chatwright.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatwright"

  # No zap stanza required

end
