# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatwright" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "5ef9a4adfc54e31990cfda9ed03db6445a1a6d50709819cbd33d3fcbd6a0147f"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f4585f548ec889313a5a937d16469140e9ab624c25b2e0ef7157d8a3f1b3b99"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0160ff81f507e563df82941fa6903b089ae41a9198047b74d934e7c5a4712679"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f705bae16ee05e4dccfcc774ef1ba9c6a30bd4e32d61bb6ef6e782d3df87e734"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chatwright"
  desc "Chatwright CLI — deterministic and AI-driven testing for conversational applications."
  homepage "https://chatwright.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatwright"

  # No zap stanza required
end
